POST http://localhost:8000 HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo
&password=bar

### Multiparts
POST http://localhost:8000 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="logo.jpeg"
Content-Type: image/jpeg

< ./logo.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--